source 'https://rubygems.org'

gem 'nekonote-framework', 'REPLACE_ME_TO_NEKONOTE_VERSION'
gem 'simple_rotate', '~> 1.2', '>= 1.2.0'
gem 'color_echo', '~> 3.1', '>= 3.1.1'

# Rack
#   Copyright (c) 2007-2016 Christian Neukirchen <purl.org/net/chneukirchen>
#   License https://github.com/rack/rack/blob/master/COPYING
gem 'rack', '~> 2.0', '>= 2.0.3'

# Liquid
#   Copyright (c) 2005, 2006 Tobias Luetke
#   License https://github.com/Shopify/liquid/blob/master/LICENSE
gem 'liquid', '~> 4.0', '>= 4.0.0'

# Puma
#   Some code copyright (c) 2005, Zed Shaw
#   Copyright (c) 2011, Evan Phoenix
#   License https://github.com/puma/puma/blob/master/LICENSE
#   Note: It seems that 'restart' doesn't work with 'bundler exec' in version 3.9.2
gem 'puma', '3.8.2'
